language: java
jdk:
    - oraclejdk8
before_install:
    - chmod +x ./Tools/travis_install.sh
    - ./Tools/travis_install.sh
install: mvn install -DskipTests=true
cache:
  directories:
    - $HOME/.m2
